import { useState, useEffect } from 'react'
import PageHeader from '@/components/layout/PageHeader'
import DataTable from '@/components/tables/DataTable'
import { useDashboardStats } from '@/hooks/useDashboardStats'
import { getOrders } from '@/services/orderService'
import type { Order } from '@/types'

export default function Reports() {
  const { stats } = useDashboardStats()
  const [orders, setOrders] = useState<Order[]>([])

  useEffect(() => {
    getOrders().then(setOrders).catch(console.error)
  }, [])

  const reports = [
    { name: 'Monthly_Financial_Report.pdf', format: 'PDF', by: 'Admin User', status: 'Completed', size: '5.4 MB' },
    { name: 'Regional_Sales_Q3.csv', format: 'CSV', by: 'Systems_Bot', status: 'Completed', size: '1.2 MB' },
    { name: 'Global_Inventory_Full.csv', format: 'CSV', by: 'Admin User', status: 'Processing', size: '--' },
    { name: 'Customer_Engagement_Q3.pdf', format: 'PDF', by: 'AI_Engine', status: 'Completed', size: '3.8 MB' },
  ]

  const totalRevenue = orders.reduce((s, o) => s + Number(o.total_amount), 0)
  const fulfilled = orders.filter(o => o.status === 'Delivered').length
  const totalOrders = orders.length

  const columns = [
    { key: 'name', header: 'Report Name', render: (r: typeof reports[0]) => <span className="font-label-md text-on-surface">{r.name}</span> },
    { key: 'format', header: 'Format', render: (r: typeof reports[0]) => <span className="text-body-md text-on-surface-variant">{r.format}</span> },
    { key: 'by', header: 'Generated By', render: (r: typeof reports[0]) => <span className="text-body-md text-on-surface-variant">{r.by}</span> },
    { key: 'status', header: 'Status', render: (r: typeof reports[0]) => (
      <span className={`px-3 py-1 rounded-full text-label-sm font-semibold ${r.status === 'Completed' ? 'bg-success/10 text-success' : 'bg-warning/10 text-warning'}`}>{r.status}</span>
    )},
    { key: 'size', header: 'Size', render: (r: typeof reports[0]) => <span className="text-body-md text-on-surface-variant">{r.size}</span> },
    { key: 'action', header: 'Action', render: () => (
      <div className="text-right">
        <button className="text-primary hover:bg-primary/10 p-2 rounded-lg transition-colors">
          <span className="material-symbols-outlined">download</span>
        </button>
      </div>
    ), className: 'text-right' },
  ]

  return (
    <>
      <PageHeader
        title="Reports Central"
        subtitle="Analyze enterprise performance and export executive summaries."
      />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-10">
        <div className="glass-card p-6 rounded-3xl flex flex-col justify-between min-h-[160px]">
          <div className="flex justify-between items-start">
            <div className="w-12 h-12 bg-primary/10 rounded-2xl flex items-center justify-center text-primary">
              <span className="material-symbols-outlined">payments</span>
            </div>
            <span className="text-success font-semibold text-label-md flex items-center gap-1">
              <span className="material-symbols-outlined text-[16px]">trending_up</span>
              +{stats?.revenueGrowth || 0}%
            </span>
          </div>
          <div>
            <div className="text-label-md font-label-md text-outline uppercase tracking-wider">Total Revenue</div>
            <div className="text-headline-lg font-headline-lg text-on-surface mt-1">${(totalRevenue / 1000).toFixed(0)}k</div>
          </div>
        </div>
        <div className="glass-card p-6 rounded-3xl flex flex-col justify-between min-h-[160px]">
          <div className="flex justify-between items-start">
            <div className="w-12 h-12 bg-tertiary-fixed text-tertiary rounded-2xl flex items-center justify-center">
              <span className="material-symbols-outlined">inventory</span>
            </div>
            <span className="text-error font-semibold text-label-md flex items-center gap-1">
              <span className="material-symbols-outlined text-[16px]">trending_down</span>
              {Math.abs(stats?.inventoryChange || 0)}%
            </span>
          </div>
          <div>
            <div className="text-label-md font-label-md text-outline uppercase tracking-wider">Inventory Value</div>
            <div className="text-headline-lg font-headline-lg text-on-surface mt-1">${((stats?.inventoryValue || 0) / 1000).toFixed(0)}k</div>
          </div>
        </div>
        <div className="glass-card p-6 rounded-3xl flex flex-col justify-between min-h-[160px] ml-border">
          <div className="flex justify-between items-start">
            <div className="w-12 h-12 bg-primary-container text-on-primary-container rounded-2xl flex items-center justify-center">
              <span className="material-symbols-outlined">auto_awesome</span>
            </div>
            <span className="text-primary font-semibold text-label-md">AI Optimal</span>
          </div>
          <div>
            <div className="text-label-md font-label-md text-outline uppercase tracking-wider">Efficiency Score</div>
            <div className="text-headline-lg font-headline-lg text-on-surface mt-1">{stats?.efficiencyScore || 0}%</div>
          </div>
        </div>
        <div className="glass-card p-6 rounded-3xl flex flex-col justify-between min-h-[160px]">
          <div className="flex justify-between items-start">
            <div className="w-12 h-12 bg-secondary-container text-on-secondary-container rounded-2xl flex items-center justify-center">
              <span className="material-symbols-outlined">shopping_cart_checkout</span>
            </div>
            <span className="text-success font-semibold text-label-md flex items-center gap-1">
              <span className="material-symbols-outlined text-[16px]">trending_up</span>
              +{stats?.fulfillmentGrowth || 0}%
            </span>
          </div>
          <div>
            <div className="text-label-md font-label-md text-outline uppercase tracking-wider">Orders Fulfilled</div>
            <div className="text-headline-lg font-headline-lg text-on-surface mt-1">{fulfilled.toLocaleString()}</div>
          </div>
        </div>
      </div>
      <div className="mt-12 glass-card rounded-3xl overflow-hidden">
        <div className="px-6 py-5 border-b border-outline-variant/10 flex justify-between items-center">
          <h3 className="font-headline-md text-headline-md text-on-surface">Recent Generated Reports</h3>
          <button className="text-primary font-semibold text-label-md hover:underline">View History</button>
        </div>
        <DataTable columns={columns} data={reports} headerClassName="bg-surface-container-low/50" />
      </div>
    </>
  )
}
